# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twist.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwist.proto\"\x88\x01\n\x08TwistMsg\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12#\n\x06linear\x18\x03 \x01(\x0b\x32\x13.TwistMsg.LinearMsg\x12\x0f\n\x07\x61ngular\x18\x04 \x01(\x02\x1a!\n\tLinearMsg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TWISTMSG']._serialized_start=16
  _globals['_TWISTMSG']._serialized_end=152
  _globals['_TWISTMSG_LINEARMSG']._serialized_start=119
  _globals['_TWISTMSG_LINEARMSG']._serialized_end=152
# @@protoc_insertion_point(module_scope)
